package advent.of.code;

import java.util.LinkedList;
import java.util.Queue;

public class Day12 {

    private static final int[][] DIRS = {{1,0},{-1,0},{0,1},{0,-1}};

    public static void main(String[] args) {
        // algorithm design
        //  1. for each character construct map as follows A -> [[x1,y1], [x2,y2], ... , [xn, yn], B -> ...]
        //  2. for each character in the map try to compute:
        //      i. size() =>  this would be number of A', B' in the map
        //      ii. perimeter => example 1
        //                AAAA
        //                BBCD
        //                BBCC
        //                EEEC
        //
        //          +-+-+-+-+
        //          |A A A A|
        //          +-+-+-+-+     +-+
        //                        |D|
        //          +-+-+   +-+   +-+
        //          |B B|   |C|
        //          +   +   + +-+
        //          |B B|   |C C|
        //          +-+-+   +-+ +
        //                    |C|
        //          +-+-+-+   +-+
        //          |E E E|
        //          +-+-+-+
        // In the first example, region A has price 4 * 10 = 40, region B has price 4 * 8 = 32, region C has price 4 * 10 = 40,
        // region D has price 1 * 4 = 4, and region E has price 3 * 8 = 24. So, the total price for the first example is 140
        //
        // //      ii. perimeter => example 2
        //                OOOOO
        //                OXOXO
        //                OOOOO
        //                OXOXO
        //                OOOOO
        //
        //          +-+-+-+-+-+
        //          |O O O O O|
        //          +-+-+-+-+-+
        //          |O X O X O|
        //          +-+ +-+ +-+
        //          |O O O O O|
        //          +-+-+-+-+-+
        //          |O X O X O|
        //          +-+ +-+ +-+
        //          |O O O O O|
        //          +-+-+-+-+-+
        // In the second example, the region with all of the O plants has price 21 * 36 = 756, and each of the four
        // smaller X regions has price 1 * 4 = 4, for a total price of 772 (756 + 4 + 4 + 4 + 4).
        // 3. for each location compute region are (i.e., number of characters around that area) * perimeter
        // 4. print out result.

        final char[][] grid_mini = {
            "AAAA".toCharArray(),
            "BBCD".toCharArray(),
            "BBCC".toCharArray(),
            "EEEC".toCharArray()
        };

        final char[][] grid = {
            "SSSSSSSSGGGGGGGGGGGGGHHHHHHHHHHHHHHRHHFFFFFFNNNNNNNNZNIIQQQQQQQQQQQQLLLLLLCCCCCCCCCCCUUUUUUSSSSSSSSSSYYYYYYYYYYFFFFFFQQQQUUUUUUUUUUUUKKKKKKK".toCharArray(),
            "SSSSSSSSGGGGGGGGGGGGGHHHHHHHHHHHHHHHHHHFFFFNNNNNNNNNNNIQQQQQQQQQQQQQLLLLLLCLLCCCCUUUUUUUUSSSSSSSSSSSSSYYYYYYYFFFFFFFFFFFQQUUUUUUUUUUUUUJJJKK".toCharArray(),
            "SSSSSSSSGGGGGGGGGGGGGHHHHHHHHHHHHHHHHHHFFFFNNNNNNNNNNNQQQQQQQQQQQQQQLLLLLLLLLCCCCCCCUUUUWSSSSSSSSSSSKKZYYYYFFFFFFFFFFFFFFFFUUUUUUUUUUUUZJJJJ".toCharArray(),
            "SSSSSSSSGGGGGGGGGGGHHHHHHHHHHHHHHHHHHHHFFFNNRNNNNNNNNNNQQQQQQQQQQQQQQLLLLLLLLOCOOCOCCUUUUCSSSSSSGSSSZZZYYYYFFFFFFFFFFFFFFFZUUUUUUBUUUUUUJJJJ".toCharArray(),
            "SSSSSSGGGGGGGGGGGGGGHGHHHHHHHVVHVVHHHHHFNNNNNNNNNNNNNNNQQQQQQQQQQQQLLLLLLLNLOOOOOOOOCUUUCCSSSSSSGSSSZZZZYYFFFFFFFFFFFFFZZZZUUUUUUBUUUUUJJJJJ".toCharArray(),
            "SSSSSSSGGGGGGGGGGGGGGGHHHHHHHVOVVVFFFFFFFNNNNNNNNNNNNNNKQQQQQQQQQQUQLLLLLLNLOOOOOOOOCCCCCCSSSSSSSSSSZZZZYYYFFFFFFFFFFFFFQZZZZUUUUUUUUUJJJJJJ".toCharArray(),
            "SSSSSWSGGGGGGGGGGGGGHHHHHHHHHVVVVVVVFFFFFFNNNNNNNNNNNNNNNQQMCQQQQQQQLLLLLLOOOOOOOOOOOCCCCCSSSSSSSSSSZZZZYYYYFFFFYYFFFFFFZZZZZZUUUFFUUUJJJJJJ".toCharArray(),
            "WWWWWWWGGGGGGGGGGGGGHHHHHHHVVVVVVVVFFFFFNNNNNNNNNNNNNNNNNSQCCPQQQWWQLLLLLGGGOOOOOOOOOCCCCCCSSSZSSSSZZZYYYYUYYYYFYFFFFFFVZZZZZZZFFFFFSJJJJJJJ".toCharArray(),
            "WWWWWWWGGGGGGGGGGGGHHHHHHHHHVVVVVVVFFFFFFNNNNNNNNNZNZNNNCCCCCCCQUDDDDDLLLLLOOOOOOVOOCCCCCCCCZZZSSSSZZZZYUUUYYYYYYYYFFFZVVZZZAAZZFFSFSSJJJJJJ".toCharArray(),
            "WWWWWGGGGGGGGGGGGHHHGHHHHHHHVVVVVVVBFFFFFFNNPNNNNNZZZNCCCCCCCCUUUDDDDLLLVVOOVVVVVVVCCCCCNNNNNNZSSSSZZZZZUUUUYYYYKKOOOOZVVZZAAAAZFFSFSSJJJJJJ".toCharArray(),
            "WWWWWWAAGGGGGGGGRRGGGHHHHHHHVVVVVJJBBFFFFNNNPPNNKZZZZZZCCCCCCCCUUUUDDLLVVVVVVVVVVVVCCCVCNNNNNNZZZZSZZZZZUUUUYYYKKKKOOOZZZZZZAAAASSSSSXXJJJJJ".toCharArray(),
            "WUUWWWWGGDGGGGGGGGGGGHHHHHXXXFVVVVVBBBBFPPPPPPNNKZZZZZZCCZCCCUUUUDUDDDVVVVVVVVVVVVVVNNNVNNNNNNNNNNNNNZUUUUUUUKKKKKOOOOZZZZZCOAASSSSSSSJJJJJJ".toCharArray(),
            "UUUUUUUUGGGGSGGGGGGGGGHHHHXXFFFVVVVBBBBBPPPPPPPNKZZZZZZZZZZUUUUUDDDDDDMMVVVVVVVVVVVVNNNNNNNNNNNNNNNNNUUUUUUUUKKKKKKKOZZZZZZOOSSSSSSSSJJJJJJJ".toCharArray(),
            "VUUUUUUUUUUUZGGGGGGGGGHXHXXXXFFBBBBBBBBBPPPPPPPPKZZZZZZZZZUUUUUUDDDDDDMMVVVVVVVVVVVVNNNNNNNNNNNNNNNNNUUUUUUUUKKKKKKKOOZOZZZZOSSSSSSSSSBOBJJJ".toCharArray(),
            "VVVUZZZZUUUZZGGGGGGGGHHXXXXXXFFBBBBBBBBBBPPPPPPPKZZZZZZZZUUUUUUUUUDDMFMMMVMMVVVVVVVVNNNNNNNNNNNNNNNNNUUUUUUUUUKKKKKKOOOOZOOOOOSSSSSSSSBOBMJM".toCharArray(),
            "VVUUZZZZZZZZZGGGGGGGGGJXXXXXXXFXBBBBBBBBBPPPPPPPPZZZZZZZZZQUUUUUUUUMMMMMMVMMMMXVVVVVVNNNNNNNNNNNNNNNNUUUUUUUURKKKKKKOOOOOOOOOOSSBSBSSBBBBMJM".toCharArray(),
            "VVUUZZZZZZZZZGGGGGGGGGGXXXXXXXXXXBBBBBBBBBBPPPPPPZZZZZZZQQQUUUUQUUUMMMMMMVMMRVVVVVVVVNNNNNNNNNNNNNNNNUUUUUUUUUKKKKKKOOOOOOOCOOOCBBBBBBBBBMBM".toCharArray(),
            "VVVZZZZZZZZZZGGGGGGGGGGGLLLLLLLXXBXXCXBBBBBPPPPYYYZZZZZKQOQQQQQQQQQMMMMMMMMMRVVVVVVVVNNNNNNNNNEEEZZZUUUUUUUUUUKKKKOOOOOOOOOCCOOCCBBBBBBBBBBM".toCharArray(),
            "VVVVZZZZZWZGGGGGGGGGGGGLLLLLLLLXXXXXXXXYYBBPPPYYYYEEEEZZZQQQQQQQQQMMMMMMMMMMVVVVVVVVVNNNNNNNNNEEZZZZUUUUUUUUUUOOOOOOOOOOOOCCCYCCCBBBBBBBBBBM".toCharArray(),
            "VVVZZZZWWWXGGGGGGGGGGGGLLLLLLLLLXXXXXXXXYYYPPPYYYEEEEEQQQQQQQQQQQQQMMMMMMMMMVVVVVVVVVNNNNNNNNNXQQQZZZUUUUUUUUUOOOOOOOOOOOOOCCCCCCCCCBBBBBBMM".toCharArray(),
            "VVVVZZZWWWWGGGGGGGGGGGGLLLLLLLLXXXXXXXXYYYYYYYYYYYEEEEEQQQQQQQQQQQQQOMMMMMMRRRRRVVVVVVNNNNNNNNXQQQZZZUUUUUUUUUUOOOOOOOOOOOCCCCCCCCCCCBBBBMMM".toCharArray(),
            "VVVVZQQWRWWQQQGGGGGGGGGLLLLLLLXXXXXXXXXYYYYYYYUUUYEEEEEQQQQQQQQQQQQOOMMMMMMRRRRRVVVVBBNNNNNNNNXXQQQZVUUUUUUUUUUPPOPOPPPPOOOCCCCCCCCBBBBBBMMM".toCharArray(),
            "VVVVQQQQWWQQQQGGGGGGGLLLLLLDDLXXDXZXYYYYYYYYYUUUUEEEEEGQQQQQQQQQQQQOOMMRRMRRRRRRRRBBBBVDDXXXXXXQQQDVVVVUUUUVVVPPPPPPPPPPPOOOCCCCCCCCBBBBBMMM".toCharArray(),
            "VVVVQQQQQQQQQQGGGSSQSLLLLLLDDXXDDXXYYYYYYYYUYUUUUUUUPEEQQQQQQQQQQQQQQMRRRRRRRRRRRRBBLLXXXXXXXXXXQQVVVVVVVVVVVPPPPPPPPPPPPPPCCCCCCCBCCCCBOMMO".toCharArray(),
            "VVVVQQQQQQQQQQQGGSSSSSSLLLLDDDDDDXYYFFFFFYYUUUUUUUUUPPPQQQQQQQQQQQQQRRRRRRRRSRSRRRBBLLXXXXXXXXXQQQVVVVVVVVVVVPPPPPPPPPPPPCCCATCGCBBBBOEOOOOO".toCharArray(),
            "VVVVQQQQQQQQQQQQSSSSSSSSLLLDDDDDDDDYFFFFYYYUUUUUUUUUUUURRQQQQQQQQQQQQRRSSSSSSSSSLLLLLLXXXXXXXXXQQQVVVVVVVVVVVVPPPPPPPPPPPPPOTTGGTBBBBOOOOOOO".toCharArray(),
            "VVVVVQQQQQQQQQQQSSSSSSSSSLDDDDDDDDDYYFFFFFUUUUUUUUUUUUUQRQQQQQQQQQQQRRRRRSSSSSSSLLLLLLLXXXXXXXXXQQQQVVVVVVVVVVPPPPPPPPPPPPOOTTTTTBBTOOOOOOOO".toCharArray(),
            "VVVVQQQQQQQQQEQSSSSSSSSSSSSDDDDDDDDYYDFFFFUUUUUUUUUUUUUQQQQQQWQQQQQQRRSSSSSSSSSSLLLLLLLDXXXXXXXXQQQQVVVVVVVZVVVPPPPPPPPPPCTTYTTTTTTTTOOOOOOO".toCharArray(),
            "VVVVVVVQQQQQQQOSSSSSSSSSGGDDDDDDDDDDDDFFFFFUUUUUUUUUUUUUUAQQUQQQQQRRRRSSSSSSSSSSLLLLLLLLXXXXXXQQQQJJVVVVVBVVVVVPPPPPPPPPPCTTTDTTTTTTTTOOOOOO".toCharArray(),
            "VVVVVVVQQQOQOOOSSSSSSSSEEDDDDDDDDDDCCCFFFFFFUUUUUUUUUUUUUAQAURQQQRRRRRSSSSSSSSSSSLLLLLLLLXXXXXXXQQJJJJJJVVVVVVVVPPPPPPPPPPTWTTTTTTTTTTSSOOEE".toCharArray(),
            "VVVVVVVVQOOOOOOSOISSSEAEDEEDDDDDDDFWCCQQQFFUUUUUUUUUUZUAAAAARRRRRRRRRRJJJSSSSSSSSSLLLLLLLXXXXXXXXJJJJJJJVVVVVVVVPPPPPPPPPPWWTTTTTTTSSTSSSEEE".toCharArray(),
            "VVVVVVVVOOOOOOOSOOQSEEEEDDEWWWDDWWWWWCQQQQUUUUUUUUUMMAAAAAAARRRRRRRYYYYYYYYSSSSSSSLLLLLLXXXXXXAXXJJJJJJJVVVVVVVVVVPPPPPPPPWWTTTTTTISSSSSSSEE".toCharArray(),
            "VVVVOOVOOOOOOOOOOOSSEEAEEEEEWWWWWWWWWQQQQQUUUUUUUUUMMAAAAAAAAARRRRRYYYYYYYYSSSSSSLLLLLLLLXXXXXXTCCCCJJCCWCCVVVVVVVPPPPPPPPWWWWTIIIISSSSSSSSS".toCharArray(),
            "VVVOOOOOOOOOOOOOOOOEEEEEEEEEEWWWWWHHWQQQQQUUUUBUUBBMMMMAAAAAABBYYYYYYYYYYYYSSSXSSLSLLLHLLXXXGXTTCCCCCJCCCCVVVVVVVVVVPPPPPWWWWIIIIIISSSSSSSSS".toCharArray(),
            "TVOOOOOOOOOOOOOOOOOEEEEEEEEEEWWWWWHWWQQQQSUUAUBBUBBBBMMAAPAPBBBYYYYYYYYYYYYYYYYYYYSSHHHHHXXTTTTCCCCCCCCCCCCVVVVVVVVKPPPPPWWWWIIIIISSSSSSSSSS".toCharArray(),
            "OOOOOOOOOOOOOOOOQOQQQNQQEEEWWWWWWWWWWQQQQQAAAUBBBBBBBMMAAPPPPBRYYYYYYYYYYYYYYYYYYYSHHHHHHXZCCCCCCCCCCCCCCCCCCVVVVKVKPPPKWWWWIIIIIIISSSSSSSSS".toCharArray(),
            "OOOOUOOOOOOOOQQQQQQQQQQQECCCCWWWWWWWWQQQAFAABBBBBBBBBMMMPPPPPRRYYYYYYYYYYYYYYYYYYYSHHHHHHZZZCCCCCCCCCCCCCCCCVVVVKKVKKKKKWWWIIIIIIIISSSSSSSSS".toCharArray(),
            "OUUOUOOOOOOOQQQQQQIQQQCCCCCCCCWWWWWWWQAAAAAAABHBBBBBMMMMMPPPPRRYYYYYYYYYYYYYYYYYYYSSHHHHHZZZZZZCCCCCCCCCCCCMVVVKKKKKKKKKKCWIIIICCCIIIISSSSSS".toCharArray(),
            "MUUWUOOOOOOOQQQQQQQQQQCCCCCCCCCCCCQQQQQAAAAAABBBBBBBBMMPPPPPPRPYYYYYYYYYYYYYYYYYYYSSHHHHHZZZZZZCCCCCCCCCCCCMKKKKKKKKKKKKCCCCICCCCCCIIISSSSSS".toCharArray(),
            "MUUUUUUUOOOOQNQQQQQQQQQQCCCCCCCQQQQQQQQAAAAAABPPBBBBBPPPCPPPPPPYYYYYYYYYYYYYYYYYYYHSHHZZZZZZZZZZCCCCCCCCCCCCKKKKKKKKKKKKCCCCCCCCCCIIIIIISSSS".toCharArray(),
            "UUUUUUMMMUOOOQQQQQQQQQQQQCCCCCCCCCQQQQQQAAAAAAAPBBHBBPPPPPPPPPPYYYYYYYYYYYYYYYYYYYHHHHZZZZZZZZZZCCCCCCCCCCCCKKKKKKKKKKKKCCCCCCCCCCCCIIIIIIIJ".toCharArray(),
            "UUUUUUUUUUOOOOQQQQQQQQQQQQCCCCCTCQQQQQQQQQAAAAAAAHHHPPPPPPPPPPYYYYYYYYYYYJJJHHHHSHHHHHZZZZZZZZZZZCCCCCCCCCPCJKKKKKKKKKKKKCCCCCCCCCCCCIIIIIIJ".toCharArray(),
            "UUUUUUUUUUUOOOSQQQQQQQQQQCCQHHHQCCQQQQQAAAAAAFAHHHHHPPPPPPPPPPYYYYYYYYYYYJHHHHHHHHHHHHZZZZZZZZZZZCCCCCCCXXCCJJGKKKKKKKKKTCCCCCCCCCCCCIIIIIJJ".toCharArray(),
            "UUUUUUUUUUUTOOSQQQQQQQQQQQQQHHHQQQQQQAAAAAAAAFFHHHHHPPPPPPPPPPYYYJKKKKJJJJJHHHHHHHHHHHHZNZZZZZZZZZCCCCCXXXXXJJGKKKKKKKKKTCCCCCCCCCCCIIIIIIIJ".toCharArray(),
            "UUUUUUUUUUUTOHSSSSQQQQQQQQQQHHHQQQQQQQAAAAAAAFHBBHHHHBPPPPPPPPYYYYYYYYKKJJJJJHHHHHHHHHHNNZZZZZZXXZCCCCXXXXXJJJKKKKKPKKKTTCCCCCCCCCCIIIIJIJJJ".toCharArray(),
            "UUUUUUUUUUUSVSSSSSSQQQQQQQQQQQQQQQQQQAAAAAAAFFFBBBBBBBPPBBPPBPYYYYYYYYKJJJJJHHHHHHHHHHNNNNNZZZZZXXXXXXXXXXJJXXXXKKKYYKYYYPPCCCCCCCCCIIIJJJJJ".toCharArray(),
            "UAUUUUUUUUUSSSSSSSSSQQQQQQQQQQEQQQQQAAAAAAAFFFFBBBBBBBBBBBPPBBYYYYYYYYJJJJJJHHHHHHHHHHNNNNGNZZPZZZAXXXXXXXXXXXXXXYYYYYYYYYPCCCCCCCJJIIIJJJJJ".toCharArray(),
            "AAUUUUUUUUUSSSSSSSSSWQQQQQQQQQEQQQQQQQAAAAAFFFBBBYYYYYYYYYYBBBYYYYYYYYJJJJJJHHHHHHHHHHNNNNNNNZZZZPAAAAAXXXXXXXXXYYYYYYYYYYYYCCCCCCJJIJIJJJJJ".toCharArray(),
            "AUUUUUUUUUSSSSSSSSSWWWQQQQQWQQQQQQQQQQQAYYYFFFBBBYYYYYYYYYYBBBPPYYYYYYJJJJJJJHHHHHHHNNNNNNNNNNDAAAAAAAAXTXXXXXXYYYYYYYYYYYIYYCCCCCCJJJJJJJJJ".toCharArray(),
            "AAUUUUUUUUWSSSSSSWWWWWWQQQQWWPPPQQXQQQHAYYYYYYYBBYYYYYYYYYYYYYYYYYYYYYJJJJJJJJHJJJJJNNNNNNNLNNAAAAAAAAAXTTTTXXXYYYYYYYYYYYYYYZCCCCCJJJJJJJJJ".toCharArray(),
            "AUUUYYYYYWWWWWSSWWWWWWWAWQQWWPPPPXXXQQQQYYYYYYYYBYYYYYYYYYYYYYYYYYYYYYJJJJJIJJJJJJJRRRRRRRRRRNAAAAAAATTTTTTTXTXXYYYYYYYYYYYYYYCAACCWWJJJJJJJ".toCharArray(),
            "AAAUYYYYYWWWWWSSWWWWWWWWWWWWPPPPXXUQQQQQYYYGGGGBBYYYYYYYYYYYYYYYYYYYYYJJJJJJJJRJJJJRRRRRRRRRRNALAAAAAATTTTTTTTTXYYYYYYYYYYYYYAWWWWCWWJJJJJJJ".toCharArray(),
            "AAAYYYYYYYWWWWWWWWWWWWWWWWWPPPXXXXUQQYQYYYYYGGGBBYYYYYYYYYYYYYYYYYYYYYHJJJJJMMRJJJJRRRRRRRRRRNAAAAAAATTTTTTTTTXYYYYYYYYKYYYYYAAWWWWWWWJJJJBJ".toCharArray(),
            "AAAYYYYYYYWWWWWWWWWWWWWWWWWWWPXXXXXYYYYYYYYGGGGGGGGBBBBBBBYYYYYYYHHHHHJJJNJJRRRRRRRRRRRRRRRRRAAAAAAAAATTTTTTTTXXYYAKKKKKKYYYAAWWWWWWWWWBBBBB".toCharArray(),
            "AAYYYYYYYYYYWWWWWWWWWWWWWWWWPPXXXXXXYYYYYYYGGGGGGGBBBGBBBBYYYYYYYHHHHHHHHMMMRRRRRRRRRRRRRRRRRAAAAAAAAAJTTTXXXXXXXXKKKKKKKKNYAAWWWWWWWWBBBBBB".toCharArray(),
            "AAYYYYYYYYYYWWWWWWWWWWWWWXWWXXXXXXXXXXYYYYGGGGGGGGGGGGGYBBBHHHHHHHHHHHHHHMMMRRRRRRRRRRRRRRRRRAAAAAAALLLLLXXXXXXXXXKKKKKKKKNWWAAWWWWWWWBBBBBB".toCharArray(),
            "AYYGYYYYYYYYWWWWWWWWWWQQQXXXXXXXXXXXXXYYYYGGGGGGGGGGGGGYYYBHHHHHHHHHHHHHHMMMRRRRRRRRRRRRRRRRRAAAAAAAALLLLXQXXQQXXKKKKKKKAWWWWAWWWWWWWWBBBBBB".toCharArray(),
            "AAYYRYYYYYYYYYWWWWWNWWQQXXXXXXXXXXXXXXXXGYGGGGGGGGGGGGGGHHHHHHHHRRHHHHHHMMMMMMMMMMJRRRRRRRRRRAAAAAAALLLLLLQQXQQXKKKKKKKKKWWWWWWWWWWWWWWWBBBB".toCharArray(),
            "AAAYYYYYYYYYYYYWNNNNWWWQQQXXWWXXXXXXXXVVGGGGGGGGGGGGFGXXXHHHHHHHHRHHHHHMMMMMMMMMMMJRRRRRRRRRRAAAAALLLLLLLLLQQQQXQKKKKKKKKKWWWWWWWWWWWWLLLBBB".toCharArray(),
            "AAAYYYYYYYYYYYYNNNNNWWWQQXXXWWWXXXXXXXVVGGGGGGGGGGGGFGXXXXHHHHHHRRRHHHHHMHMMMMMMMMJJJJJJJJAAAAAALLLLLLLLLLLLQQQQQKKKKKKKKKKWWWWWWWWWWWWLLLBB".toCharArray(),
            "AAAAAYYYYYYYYYNNNNNNNNNQQQXXWWWXWXXXXVXVGGGGVGGGGGGGGXXXHHHHHQHHRRHHHHHHHHHMHSMMJMJJJJJJJAAAAAAALLLLLLLLLLLLJJQQQQQKKKKKKKKKKGGGWWWWWWWLLBBB".toCharArray(),
            "AAAAAAYYYYAYNNNNNNNNNNNQQQQQWWWWWWXXXVVVGGGGVGGGGGGOXXXXZHHHQQQHRHHHHHHHHHHHHSMMJJJJJJJJJJJAAAAALLLLLLLLLLLLJJQQQQQKKKKKKKKKKGGGWWWWWCWCLLBB".toCharArray(),
            "AAAAAAYYYYAAANNNNNNNNNQQQQQWWWWWWWXXVVVVVGGVVGGGGGGOXXXXXHHSQQQHHHHHHHHHHHHHHHJJJJJJJJJJJJJPPAAALLLLLLLLLLJJJJQQQQQQKKKKKKKKKGGGGCCWCCCCLLBB".toCharArray(),
            "AAAAAYYYYAAAANNNNNNNQQQQQQQQWWWWWWXXWVVVVVVVVVVGVVVVRRRWSSSSQQQQQQHHHHHHHHHJJHHHJJJJJJSSSJJPPPPPPPLLLLLLLJJJJJQQQJKKKKKKJKKKGGGGGGCCCCCCCCBB".toCharArray(),
            "AAAAAAAYYAAAANNNNNNNQQQQQQQWWWWWWWWMWWWVVVVVVVVVVVVVRRWWWSSQQQQQQNNNHHHHHHJJJHJJJJJJJSSSSSSPPPPPPPLLLLLJLJJJJJJJJJKKKKKKJKKKGGGGGGGCCCCCCCAB".toCharArray(),
            "AAAAAAAAAAAAAANNNNNSSQQQQQWWWWWWWWWWWWWVVVVVVVVVVVWWWWWWSSQQQQQQQNNNHHNNNNNNHHJJJJJJSSSSSSPPPPPPPPLLJJJJJJJJJJJJJJJKKKKJJJKKGGGGGGGCCCCCCAAB".toCharArray(),
            "AAAAAAAAAAHHAAANNNNSSQQQQQWWWWWWWWWWWWVVVVVVVVVVVVWWWWWSSSSSQNNNNNNNNNNNNNNNJHJJJJJJSSSSSSPPPPPCPLLLJJJJJJJJJJJJJJKKKKJJJJJJGGGGAGGCCCCCCCAA".toCharArray(),
            "AAAAAAAAAAHWHNNNNNNSSSSQQWWWWWWWWWWWWWVVVVVVVVVVVWWWWWWSSSSQQNNNNNNNNNNNNNNNJJDDJJDDESSSSSSPSSCCCLLLJJJJJJJJJJJFJKKKJKJJJJJTGGGGAAAAACCACAAA".toCharArray(),
            "AAAUAAAAAHHHHHNNNNNSSSQQQQQWDWWWWWWWWWWWVVVVVVVVVVWWWWWSSSQQQNNNNNNNNNNNNNNNDDDDDDDDESSSSSSSSSSVVJVIJJJJJJJJJJJJJJJJJJJJJJJJJGGGSAAAAAAAAAAA".toCharArray(),
            "AAAUUUUUAHHHHNNNNSSSSSDQQQQDDWWWWWWWWWWWVVVVVVVVCCWWWWWWSSQQQNNNNNNNNNNNNNNNDDDDDDVDSSSSSSSSSSSGVVVIJJJJJJJJJJJJJJJJJJJJJJJJJGIGSAAAAAAAAAAA".toCharArray(),
            "UUUUUUUUUUHHHVVNSSSSSSDDDQQQDDDWWWWWWWWVVVVVVVVVCCCWWWWWSQQQQQQNNNNNNNNNNNNNDDDDDDVSSSSSSSSSSSOVVVVVJJJJJJJJJJJJJJJJJJJJJJJJJIIIAAAAAAAAAAAA".toCharArray(),
            "UUUUUUUURHHHHSSNSSSSSDDDDDDDDDDDDWWWWWWWVVWVVVVVCCCWOOOHHYYQQQQNNNNNNNNNNNNNDDDDDDSSSSSSSSSSSSSVVVVVIIJJJJJJJJJJJJJJJJJJJJJJIIIAAAAAAAAAAAAA".toCharArray(),
            "UUUUUUUUUUHHHSSSSSSSDDDDDDDDDDDDDWWWWWWWWWWWVWFFFCCCHHHHHYYQQQQNNNNNNNNNNNNNDDDASSSQSSSSSSSSSSSVVVVVVIIJJLJJJJJJJJJJJJJJJJJIIIIAAAAAAAAAAAAA".toCharArray(),
            "UUUUUUUUUUHHHSSSSSSSSSSDDDDDDDDDDWWWWWWWWWWWFFFFFCCHHHHHHYYYQQQNNNNNNNNNJDDDDDDDSSSSSSSSSSSSSSSSVVVVVVIJJLGOJJJJJDJJJJJJJJIIIIIAAAAAAAAAAAAA".toCharArray(),
            "UUUUUUUUUUHHSSSSSSSSSOSDDDDDDDDDDWWWWWWWWWWWWFFFFCHHHHHHHHXXXXXQQQXNNNNNJDDDDDDDSUSCSSSSSSSSSSSVVVVVVVVVGGGOOJBJJDDDJJJJJJJJXXXXTAAAAAAAAAAA".toCharArray(),
            "UUUUUUUUUUHHSSSSSSSSOOSDDDDDDDDDDWWWWWWWWWWWWWWFFCCHHHHHHXXXXXXXXXXXXXJJJDDDDDDDDDDSSSSSSSFSSSSVVVVVVVVVGGGOOGJJDDDDDDJJJJJJXXAAAAAAAAAAAAAO".toCharArray(),
            "UUUUUUUUUHHSSSSSSSSSODSDDDDDDDDDDWWWWWWWWWWWWWWFQHHHHHTHHXXXXXXXXXXXXXJJJDDDDDDDDDSSSSSSSSFSSSSVVVVVVVVVGGGGGGJJDDDDDPJDDDDJXXXAUXAAAAAAAAAO".toCharArray(),
            "UUUUUUUUUHHHNNSSSSSSOOODDDDDDDVDDWWWWWWWWWWWWWWFHHHHHHHXXXXXXXXXXXXXXXJJJJJDDDDDDDSSSSSSOTTTSSSVVIIVVGVGGGGGGGGJDDDJJJJJDDDXXXXXXXAAAAAAAAAO".toCharArray(),
            "UUUUUUUUNNHNNSSSSSSSOOVVDVDVDVVVDWWWWWYWWWWWWWWWWWHWHHNXXXNNNNXXXXXXXJJJJJSDDDDDDDSADISTTTTTTTTVIIIIIINGGGGGGGGGDDDDDDJJDDDXXXXXXXSSAAAAAOOO".toCharArray(),
            "UUUUUUUUUNNNNNSSSSVVVOVVVVVVVVVVWWWWWWYYYYWWWWWWWWWWHHNNXXNNNNNNXXXXWWWJJJSDDDDDDDDDDDSSSTTTTTVVIIIIPGGGGGGGGGGDDDDDDDDDDDDZXXXXXXSVSAAOOOOO".toCharArray(),
            "UUUUUUUUUNNNNNSXVVVVVVVVVVVVSSSSWWWWWWWWYWWWWWWWWQQQINNNXNNNNNNNFXXXXJJJJJDDDDDDDDDDDTTTTTTTTTTVIIIIIIIGGGGGGGGGGDDDDDDDDDDXXXXXXXSVVAAOOOOO".toCharArray(),
            "RURRRRUUUNNNBBVVVVVVVVVVVVVVVSSSSWWSSSYYYWYYWWQQWQQQQNNNNNNNNNNNNXIIIIIJJJDJDDATTDDDTTTTTTTTTTTTMIIIIIIGGGGGGGGGGGDDDDDDDDDDXXXPXVSSVVVVOOOO".toCharArray(),
            "RRRRRUUUBBNNBYVVVVVVVVVVVVSSVSSSSSSSSSYYYYYYWQQQWQQQQQNNNNNNNNNNNIIIIIBJJJJJDDTTTTTTTTTTTTTTTTTTMIIIIIIIIGGGGGGGGGGGDDDDDDDDXXXXXVVVVVVVVOOO".toCharArray(),
            "RRRRRRUUBBNNBYVVVVVVVVVVVVSSSSSSSSSSSSSSYYYYWQQQQQQQQCNNNNNNNNNBBBIIBBBJJJJJJJTTTTTTTTTTTTTTTTTTMIIIIIIIIGGGGGGGGGWDDDDDDDDDUUXYVVVVVVVVVVOO".toCharArray(),
            "RRRRRRRRRBBBBYVVVVVVVVVVVSSSSSSSSSSSSSSSYYYQQQQQQQQQCCNNNNNNNNNBBBIIBBBBJJJJJJJTTTTTTTTTTTKKKTTTMIIIIIIIGGGGGGGGGGDDDDDDDDUUUUXMKVVVVVVVVVVV".toCharArray(),
            "RRRRRRRRRBBBBYYYVVVVVVVVVSSSSSSSSSSSSSSSYYYYYYQQQQQQQQNNNNNNNNNNNBBBBBBBJJJJJJJTTTTTTTTTTTKKKTTIIIIIIIIIGGGWGGGGGGGDDDDUUUUUUMMMVVVVVVVVVVVV".toCharArray(),
            "RRRRRRBBBBBBBYBVVVVVVVMVVVMMMSSSSSSSSSSSYYYYYYQQQQQQQQNNNNNNNNNNBBBBBBBJJJJJJJTTTTTTTTTTTKKKXXTIIIKIIIIIWGWWWWWGGGLDDDDDDUUMMMMMMNVVVVVVVVVV".toCharArray(),
            "RRRRRRRRBBBBBBBVVVVVVVMVVMMMMMSSSSSSSSSSSYYYYYQQQQQQQQQNNNNNNNNNBBBBBBBBJJJJJJTTTTTTTNTTTKKKKKDIKKKKIIKKWWWWWWWWWWLDWDDDDCUUUMMMMMVVVVVVVVVV".toCharArray(),
            "RRRRRRRRBBBBRBRRTTVVMMMMMMMMMMSSSSSSSSSSSYYYYNNNQQQWQQQNNWJNNNNNBBBBBBBBBBJJJJJNTTTNNNKKYKKKKKKKKKKKKKKKKWWWWWWWWWWWWWDCDCMMMMMMMMVVVVVVVVVV".toCharArray(),
            "RRRRRRRBBBBRRRRRTTMVMMMMMMMMMMSSSSSSSSSYYYWWYWNNNQQWQAQWWWJJJNNJBBBBBBBBBBJJJNNNNNNNNNNKKKKKKKKKKKKKKKWWWWWWWWWWWWWWWWWCCCRMMMMMMMVVVVVVVVVV".toCharArray(),
            "RRRRRRRBBBRRRRRHTMMMMMMMMMMMMSSSSSSSSYSYYYWWWWWWNQQWWWWWWJJJJNJJBBBBBBBBBBBBBNNNNNNNNNNNNKKKKKKKKKKKKKKWWWWWWWWWWWWWWWCCCCCMMMMVVVVVVVVVVVVN".toCharArray(),
            "RRRRDRRRBRRHRHHHTZZZZZMMMMMMMSSSSSSSSYYYYYWWWWWWWQQWWWWWWWWWJJJJBBBBBBBBBBBBBBNNNNNNNNNNNSKKKKKKKKKKKKKWWWWWWWWWWWWWWIICCCCCMMVVVVVVVVVVVVVV".toCharArray(),
            "DDDDDRRRRRRHHHHHTZZZZZMMMMMMMMSSSSSSSYYYYWWWWWWWWWWWWWWWWWWJJJJRRBNNBBBBBBBBBNNNNNNNNNNNNKKKKKKKKKKKKKWWWWWWWWWWWWWWWIIIICCCCVVVVVVVVVVVVVVV".toCharArray(),
            "DDDDDRRRRRRHHHHHHHZZZZZZZZMMMSSSSYYYYYYYYWWWWWWWWWWWWWWDWJJJJRRLRNNNBBMMMMMBBNNNNNNNNNNNNPPKKKKKKKKKKKKKWWWWWWWWWWWWWIIICCCCCVVVVVVVVVVVVVVV".toCharArray(),
            "DDDDDDRRRRRHHHHHHZZZZZZZKMMMMMMMYYYYYYYYYWWWWWWWWWWWWWWWWJJJJRRRRRNRBBBMMMMBBNNNNNNNNNNNNPPPKPKKKKKKKKKKKWWWWWWWUUWWWIICCCCCCVVVVVVVVVVVVVVV".toCharArray(),
            "DDDDDDDRRRRHHHHHHHZZZZZZZMZMMMMMYYYAYYYYYYWWWWCCCWWWWWWWWJJJJJRRRRRRRBBMMMMNNNNNNNNNNNNTNPPPPPPAKKKKWWWKHWWWWWWWUUSSWIISSSSSCCCVVVVVVVVVVVVV".toCharArray(),
            "DDDDDDRRRRRVHHHHZZZZZZZZZZZZMMMMMAAAYYYYYAAAAWDCWWWWWWWWWWJJJRRRRRRCRMMMMMMNNNNNNNNNNNNNNPPPPAAAKKKKKKKHHHWWWWWWSSSSSSISSSSCCCCVVVVVVVVVVVVV".toCharArray(),
            "DDDDRDRRRRVVVVHHZZZZZZZZZZZZMMMMWWAAAAAYYAAAAACCWWWWWWTWWWWJRRRRRRRRRMMMMMMMNNNNNNNNNNNNNPAAAAAAAAKKKHHHHHHHHHHYNNSSSSSSSSCCCCVVVVVVVVVVLLVV".toCharArray(),
            "DDDDDDDDRRVVVVVVYYVZZZZZZZZZBMMMAAAAAAAAAAABAACCCWCCWTTWWQWRRRRRRRRRRMRMMMMMNNNNNNNNNNNPPPPPAAAAAAAAAHHHHHHHHHYYYNNSSSSSSSCCCCVVVVVVVVVLLLVL".toCharArray(),
            "DDDDDDDDDRRVVVVVVVVVZZZZZZZZZMMEAAAAAAAAAAAAACCCCCCCWTTTWWRRRRRRRRRRRRRRMMMMMNNNNNNNNNPPPPPPAAAAAAAAAAHHHHHHYYYYYNNSSSSSSSSSCCVVVVVVVVLLLLLL".toCharArray(),
            "DDDDDDDOOVVVVVVVVVVVVZZZZZZZJZZZCAAAAAAAAAAAACCCCCCCTTTLLRRRRRRRRRRRRRRRRRMMMMNNNNNNPPPPPPPAAAAAAAAAAAAHHHHHYYYYYYYVYSYSSSSCCCCVZVVVVVVLRLLL".toCharArray(),
            "DDDDDOOOOVVVVVVVVVVVVZZZZZZZZZCCCAAAAAAAAAAAACCCCCCCCCCCXRRRRRRRRRRRRRRRRMMMMMNNNPPPPPPPPPAAAAAAAAAAAHHHYYYYYYYYYYYYYSYYYYYCCCVVZVVVVVVLRRLL".toCharArray(),
            "DDDOOOVVVVVVVVVVVVVVVZZZZZZZZZCAAAAAAAAAAAAAACCCRRCCCCXNXRRRRRRRRRRRRRRRMMMMMMNPPPPPPPPPPPALAAAAAAAAAAAHYYYYYYYYYYYYYYYYYYYCCCVRVVVVVVVRRLLL".toCharArray(),
            "OODDOVVVVVVVVVVVVVVVJJZZZZZZZZCAAAAAAAAAAAAAAACHROOOQQXXXXXRRRRRRRSRRRRBSSMMMGPPPPPPPPPPPPPAAAAAAAAAAAHYYOYYYYYYYYYYYYYYYYYYYCRRRRRVVVRRRLLL".toCharArray(),
            "OOOOOOOOVVVVVVVVVVVVJZZZZZZZZCCCCCCAAAAAAAAAAAARRROXXXXXXXXXRRKRRSSSSSRRSSSSGGPPPPPPPPKKKKKAAAAAAAAAAAHOOOYYYYYYYYYYYYYYYYYYYCCRRRRRRRRRRRRR".toCharArray(),
            "OOOOOOOOVVVVVVVVVVVVJZZKKZZZGKKKCCAAAAAAAAAAAAARRROOXXXXXXXGGGSSSSSSSSSSSSSCGXGPPKPPPPKUKKKAAAAAMMMMMOOOOOYOYYYYYYYPYYXXXYYYCCRRRRRRRRRRRRRR".toCharArray(),
            "OOOOOOOVVVVVVVVVVVVVVVVKKKZZGKKKCCAAAAAAAAAAKRRRROORXXXXXXXXGGGGYSSSSSSSSSSSGGGGPKPPPKKKKKKKAAAMMMMMOOOOOOOOOYYYYYYPXXXXXXXYYCRRRRRRRRRRRRRR".toCharArray(),
            "OOOOOOOVVVVVOVVVVVVVVKKKKKKKKKKCCCARAAAAAALARRRRROORXXXXXXXXXGGGGRRRRSSSSSSSGGGGGKKKKKKKKKKKAAAMMMMMOOOOOOYOYYYYYYYYYXXXXXXYYYYRRRRRRRRRKKKY".toCharArray(),
            "OOOOOOOOVOOOOVVVVVVVKKKCCKKKKKKCCCGGHAAGALLLRRRRRRRRRXXXXXXXXGGGGRRRRSSGSSSSGGGGGFKKKKKKKKKKKAAMMMMOOOOOOOYYYYYYYYXXXXXXXXYYYYYRRRRRRRRRKKKK".toCharArray(),
            "OOOOOOOOOOOOOOVVVJJVKKKCCKKKKKKGCGGGGAGGGLLRRRRRRRRXXXXXXXGGGRRRRRRRRRSGRSSSGGGGGGKKKKKKKKKKKKAOOOOOOOWOYYYYYYYYYXXXXXXXXXXXXRRRRRRRRRRRRKKK".toCharArray(),
            "OOOOOOOOOOOOVVVJVJJJKCCCCCKAEEEGGGGGGGGGGGLRRRRRRRRKXXXXXXGGGRRRRRRRRRSGGGCCGGGGGGGGKKKKKKKKKKKOOOOOOWWWWBYYYYYYYXXXXXXXXXXXXXRRRRRRRRRRRKVV".toCharArray(),
            "OOOOOOOOOOOOOVVJJJJJJJCCCCKAAAAGGGGGGGGGGFRRRRRRRRKKXXXXXGGGGRRRRRRRRRGGGGCCCGGGGGGGGKKKKKKKKKOOOOOOWWWWWBWTTYYYYYXXXXXXXXXXXXRRRRRRRRRRRVVV".toCharArray(),
            "OOOOOOOOOOOOOOJJJJJJJJCCCCVAAAGGAAGGGGGAARRRRRRRRRKXXXXXXGGGGRRRRRRRRRGGGCCCCCGGCGGGGGKKKKKKKOOOOOOWWWWWWWWWTTTTYXXXXXXXXXXXXXRRRRRRRVRRVVVV".toCharArray(),
            "OOOOOOOOOOOOJJJOJJJJJCCCCAAAAAAAAAGGGGAAARRRRRRRRRKKXXXGGDGGGRRRRRRRRRGGCCCCCCCCCGGGGKKKKKKKKOOOOOWWWWWWWWWWWTXXXXXXXXXXXMXXXXHHRRVVVVVVVVVV".toCharArray(),
            "ONOOONOOOOOOOOOOIJJJJCCCAAAAAAAAAAAGGAAAARRRRRRRRRRKXXXGGRRRRRRRRRRRRRGGCCCCCCCCCGGGGGGKKKKKZOOOOOOWWOWWWWWWWTXXXXXXXXXXMMMMMMMHRRVVVVVVVVVV".toCharArray(),
            "NNOOONNOONNIIIIIIJJJCCCFAAAAAAAAAAAAGAARRRRRRRRRRRRRRUXZKRRRRRRRRRRRRGGCCCCCCCCCCGGGGGGKKKKKKKOOOOOOOORRWWWWWTTXXXXXXXXXXMMMMMMHRRRVVVVVVVVV".toCharArray(),
            "NNNNNNNNNNUUIIIIIIIJCCCCCAAAAAAAAAAAAARRRRBRRRRRRRRFFKXKKRRRRRRRRRRGQCCCCCCCCCCCCCGGGGGGGGKKKKOWOOOOOWRRWWWWTTXXXXXXXXXXMMMMMEEMMJJVVVVVVVVV".toCharArray(),
            "NNNNNNNNNUUUIIIIIIJJJJJJCJAAAAAAAAAAAARPPRRRRRRVVRRFFKKKKRRRRRRRRRRQQCCCCCCCCCCCCCCGGGGGGKKWWWOWWWOOWWRRTTTTTTTXXXXXXXQMMMMMMMMMMJJVVVVVVVVV".toCharArray(),
            "NNNNNNNNNUUUIIIIIIJJJJJJJJANAAAAAAAAPPRPPPRRLRRRVVRKKKKKPRRRRRRRRRGGQCCCCCCCCCCCCGGGGGGGGGGWWWWWWWWWWRRBBBBBBBBBBXXXQQQQMMMMMMMMMJJVPVVVVVVV".toCharArray(),
            "NNNNNNNNNNUUUIIIIIIUUJJJJJAAAJAAAAAAPPPPPPPPRRVVVVRKKKKKPRRRRRRRRRGQQCCCCCCCCCCCCCGGGGGGGGGWWWWWWWWWWRRBBBBBBBBBBBBBBBBBQMMMMMMMMMPPPPPVVVYV".toCharArray(),
            "NNNNNNNNNNUUUIIUIIIUUUJJJJJJAJAAAAPAPPPPPPPKKVVVVKKKKKKKPRRRRRRRRRCCCCCCCCCCCCQUUCGGGGGXXXWWWWWWWWWRRRBBBBBBBBBBBBBBBBBBQMMMMMMMEMMPPPPPPVYV".toCharArray(),
            "NNNNNNNUUUUUUUUUUIIUUUUUJJJJJJAAAAPPPPPPPPKKKKKKVVKKKKKKPRRRRRRRRRCCCCCCCCCCCCUUUUUUGGXXXXXWWWWWWWRRRRBBBBBBBBBBBBBBBBBBQMMMIIMMEMLPPPPPPPYY".toCharArray(),
            "NNNNNNNNUUUUUUUUUUUUUUUUUJJJJAAAAPPPPPPPPPPKKKKKKKKKKKKKPRRRRRRRRRCCCCCCHHSSUUUUUUUUGGGXXXXWFFWWWWRYRRBBBBBBBBBBBBBBBBBBBBBBIIJELLLLLLPPYYYY".toCharArray(),
            "NNNNNNNUUUUUUUUUUUUUUUUIIHJAAAAAAGPPPPPPPPPPKKKKKKKKKKKKKPMPPCCCCCCCCCHHHHHSSUUUUUUUUUXXXXXFFFWFFRRRRRRBBBBBBBBBBBBBBBBBBBBBIIJJLLLLLLLPPYYY".toCharArray(),
            "NNNNNNNUUUUUJUUUUUUUUUUUHHHHHHAAAAAPPPPFFFFKKKKKKKKKKKKKKKPPCCCCCCCCCCHHHHHSSUUUUUUUUUXXXXXVFFFFFRRRRRRRRRRBBBQBBBBBBBBBBBBBJIJJLLLLLLLPYYYY".toCharArray(),
            "NNNNNNNNUUJJJUUUJUUUUUUUHHHHHHAAAAAEPPPFFFFKKKKKKKKKKKKKKKPPCCCCCCCCCHHHHHHSHURUUUUUUXXXXXXVVFFFFFFRRRRRRRRBBBQBBBBBBBBBBBBBJJJJLLLLLLLYYYYY".toCharArray(),
            "NNNNNNNNUUJJJJJJJJJJUUUUIHHHHHAEEEEEPPFFFFFKKKKKKKKLLLKKKKKPCCCCCCCCCHHHHHHSHUYYYYYYYYYYUXFFFFFFFFFFFRRRRNNBBBNBBBBBBBBBBBBBJJJJLJLLLLLYYYYY".toCharArray(),
            "NNNNNNENUJJJJJJJJJDDUDDHHHHHHEEEEEEEPPFFFFFKKKKKLLLLLLKKKKKKCCCCCCCCCHHHHHHHHGYYYYYYYYYYYYYYYYYFFFFFFRFRFNNBBBNBBBBBBBBBBBBBAJJJJJLLLLLLYYYY".toCharArray(),
            "NNNNNNNNSSSJJJJJJJDDDDDDHHHHHHEEEEEEFFFFFFFFKZKKLLLLLLKKKKKKKCCKCKCCCHHHHHHHGGYYYYYYYYYYYYYYYYYFFFFFFQQQQQQBBBQBBBBBBBBBBBBBAJJJJJJJLLLQQQQY".toCharArray(),
            "KNNENSCSSJJJJJJJJJDDDDDDDHHHHEEEEEEFFFFFFFCKKKKKLLLLLKKKKKKKKKKKKKKKHHHHMHHZGGYYYYYYYYYYYYYYYYYFFFFFFQQQQQQQQQQFFCCFFFFAAAAAAAJJJJJJLQQQQQQQ".toCharArray(),
            "NNNENSSSSJJJJJJJJJDDDDDDDHHHHEEEEEHFFFFFFFLLKLLLLLLLKKKKKKKKKKKKKKKKCTCCCCZZZZYYYYYYYYYYYYYYYYFFFFFFQQQQQQQQQQQNFFFFFFFAAAAAAJJJJJJQQQQQQQQQ".toCharArray(),
            "EEEEESSSSSJJJJJJJJSDDDDDHHHHHHHEEEHXXFVVFFLLKLLLLLLLLKKKKKEEKKEEKKEKCCCCCCCZZZYYYYYYYYYYYYYYYYFFFFFFQQQQQQQQQQQFFFFFFFFAAAAAAJJJJJQQQQQQQQQQ".toCharArray(),
            "JEEJEJJJJJJJJJJJJJSDDDDDHHHHHHHEEEHXXXLVFLLLLLLLLLLALEEEEKEEEEEEKKEKCCCCCCCZZZZYYYYYYYKKKKKKKKKFFFFFQQQQQQQQRRRBBRFFFFFAAAAAAJJJRRQQQQQQQQQQ".toCharArray(),
            "JEJJJJJJJJJJJJUUSSSSDDDDHHHHHHHHHHHHXXLLLLLLLLLLLLLAAEEEEEEEEEEEEEEECCCCCCCCCCZYYYYYYYKKKKKKKKKKFFFFQQQQQQQQQQQQQRFFFFFFAAAAAJJJJQQQQQQQQQQW".toCharArray(),
            "JJJJJJJJJJJJFFUUSSSSSDHHHHHHHHHHHHHXXXXLLLLLLLLLLLAAAEEEEEEEEEEEEECCCCCCCCCCCCCYYYYYYYKKKKKKKKHFFFFFFQQQQQQQQQQQQRRRGFFGGAAMMMXXHQQQQQQQQQQW".toCharArray(),
            "JJJJJJJJJJJJJUUUSSSSDDHHHHHHHHHHHHYHXXXXLXLLLLLLLAAAAAAEEEEEEEEECCFCCCCCCCCCCCCYYYYYYYKKKKKKKKKFFFFGGQQQQQQQQQQQQRGGGGGGGXMMXXXXXQQQQQQQQQQQ".toCharArray(),
            "UJJJJJJJJJJBBUUUSSSSSHHHHHHHHHHHHHHHXXXXXXBBBBLLLAAAAEEEEEEEEEEECCCCCCCCCCCCCCCCCCPPKKKKKKKKKKKKKKGGGQQQQQQQQQQGGRRGGGGGXXXXXXXKXXQQQQQQQQQQ".toCharArray(),
            "JJJJJJJJJJJBSSSSSSSSSHHHHHHHHHHHHHAHXXXXXXXBBBBAAAAAAAAEEEEEEEEECCCCCCCCCCCCCCCCCPPPKKKKKKKKKKKKKGGGGQQQQQQQQQQGGGGGGGGXXXXXXXXXXXCQQQQQQQOQ".toCharArray(),
            "KJJJJJJJJJJSSSSSSSSSSHHHHHHHHHHHHHHHXXXXXXBBBBBBBBAAAAAEEEEEEEEOOOCCCCCCCCCCCCPPPPPPPKKKKKKKKKKKKGGGGQQQQQQQQQQGGGGGGGGGXXXXXXXXXYQQQQQQQQQU".toCharArray(),
            "KJJJJJJJJJJSSOOSSSSSSAHHHHHHHHHHHHHHHXXXXXBBBBBBBAAAAAAEEEEEEEEOOOCCCCCCCCCCCPPPPPPPPPKKKKKKKKKKKGGGGQQQQQQQQQQGGGGGGGXXXXXXXXXXXYQQQQQQQQQU".toCharArray(),
        };

        boolean[][] visited = new boolean[grid.length][grid[0].length];
        long totalPrice = 0;

        for (int i=0; i<grid.length; i++) {
            for (int j=0; j<grid[0].length; j++) {
                if (!visited[i][j]) {
                    totalPrice += computePrice(grid, i, j, visited);
                }
            }
        }

        System.out.println(totalPrice);
    }

    /**
     * Computes the price of a region in the grid as area * perimeter using BFS.
     *
     * @param grid      the grid of region characters
     * @param x         starting x-coordinate
     * @param y         starting y-coordinate
     * @param visited   tracks visited cells
     * @return the region's price (area * perimeter)
     */
    private static long computePrice(char[][] grid, int x, int y, boolean[][] visited) {
        final char regionCharacter = grid[x][y];
        final Queue<int[]> bfsQueue = new LinkedList<>();

        bfsQueue.offer(new int[]{x, y});
        visited[x][y] = true;
        int area = 0;
        int perimeter = 0;

        // BFS
        while(!bfsQueue.isEmpty()) {
            final int[] currentRegion = bfsQueue.poll();
            area++;
            final int currentX = currentRegion[0], currentY = currentRegion[1];
            for (int[] direction: DIRS) {
                final int nextX = currentX + direction[0], nextY = currentY + direction[1];
                // check for valid movements to grid (if we are not out of ...)
                if (nextX < 0 ||
                    nextX >= grid.length ||
                    nextY < 0 ||
                    nextY >= grid[0].length ||
                    // same region character!!
                    grid[nextX][nextY] != regionCharacter) {
                    // if so we increase perimeter
                    perimeter++;
                } else if (!visited[nextX][nextY]) {
                    // if not visited we add to queue :)
                    visited[nextX][nextY] = true;
                    bfsQueue.offer(new int[]{nextX,nextY});
                }
            }
        }
        return (long) area * perimeter;
    }
}
